language: node_js
node_js:
  - "0.10"
env:
  - [
      {secure: ""},
      {secure: ""}
    ]
before_script:
  - "./node_modules/.bin/install_sauce_connect"
  - "./node_modules/.bin/travis_start_sauce_connect"
script:
  - "make test_midway_sauce_connect"
  - "make test_e2e_sauce"
